### ISSUE TITLE
how to open onvif camera in java

### ISSUE THREAD

**Issue by sachinrke** [fpompermaier/onvif#11]
hiii,
i want to open my ptz camera in java using your library. please tell me how to open camera.
thank you in advance.

**Comment by fpompermaier** [comment]
If you want to use an Ovif device try to have a look at https://github.com/fpompermaier/onvif/blob/master/udoo-bot/src/main/java/org/udoo/telegram/bot/TelegramMsgHandler.java. 

You need to write something like:
```java
try {
	System.out.println("Connect to camera, please wait ...");
	OnvifDevice cam = new OnvifDevice(deviceIp, user, password);
	System.out.printf("Connected to device %s (%s)\n", cam.getDeviceInfo(), deviceName);
} catch (ConnectException | SOAPException e1) {
	System.err.println("No connection to device with ip " + deviceIp + ", please try again.");
	System.exit(0);
}
```

Then you can take a picture from the camera with:
```java
MediaUri sceenshotUri = cam.getMedia().getSnapshotUri(profileToken);
File tempFile = File.createTempFile("tmp", ".jpg");
FileUtils.copyURLToFile(new URL(sceenshotUri.getUri()), tempFile);
```

**Comment by richard-austin** [comment]
Hi 

I've been using your library successfully in my CCTV NVR for just over a year. For a couple of days last week, the Onvif discovery was failing. This was due to w3.org testing a planned dropping of support for http requests, which they would send a 301 (or similar) redirect. The problem is that my cameras use http urls for the schemas and the Onvif library does not redirect by default. Is there a way it can configured to follow redirects? 

w3.org are planning to make this change permanent in the near future which would stop Onvif discovery working altogether.

Thanks in advance
